name: Deploy to ECS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ECR_URI }}

    - name: Build and push Docker image to ECR
      run: |
        docker build -t ${{ secrets.ECR_URI }}:${{ github.sha }} .
        docker push ${{ secrets.ECR_URI }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task@v2
      with:
        cluster: datatinga-webapp-beta-cluster
        task-definition: datatinga-webapp-beta-task-definition
        service: datatinga-webapp-beta-service
        image: ${{ secrets.ECR_URI }}:${{ github.sha }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
